import Img1 from "../images/2.jpg"
export const Products = [
    {
        id:1,
        title:"Mens-shirt",
        desc:"designer material",
        img:Img1,
        gender:"Men",
        price:120 ,
    },
    {
        id:2,
        title:"Mens-shirt",
        desc:"designer material",
        img:Img1,
        gender:"Women",
        price:140,
    },
    {
        id:3,
        title:"Mens-shirt",
        desc:"designer material",
        img:Img1,
        gender:"Men",
        price:160,
    },
    {
        id:4,
        title:"Mens-shirt",
        desc:"designer material",
        img:Img1,
        gender:"Women",
        price:120,
    },
    {
        id:5,
        title:"Mens-shirt",
        desc:"designer material",
        img:Img1,
        gender:"Men",
        price:100,
    },
    {
        id:6,
        title:"Mens-shirt",
        desc:"designer material",
        img:Img1,
        gender:"Women",
        price:120,
    },
    {
        id:7,
        title:"Mens-shirt",
        desc:"designer material",
        img:Img1,
        gender:"Men",
        price:240,
    },
    {
        id:8,
        title:"Mens-shirt",
        desc:"designer material",
        img:Img1,
        gender:"Men",
        price:120,
    },
    {   
        id:9,
        title:"Mens-shirt",
        desc:"designer material",
        img:Img1,
        gender:"Women",
        price:180,
    },
    {   
        id:10,
        title:"Mens-shirt",
        desc:"designer material",
        img:Img1,
        gender:"Women",
        price:190,
    }
]